/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NgComponent {
        "url": string;
    }
}
declare global {
    interface HTMLNgComponentElement extends Components.NgComponent, HTMLStencilElement {
    }
    var HTMLNgComponentElement: {
        prototype: HTMLNgComponentElement;
        new (): HTMLNgComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ng-component": HTMLNgComponentElement;
    }
}
declare namespace LocalJSX {
    interface NgComponent {
        "onLoadingError"?: (event: CustomEvent<any>) => void;
        "onNgMessage"?: (event: CustomEvent<any>) => void;
        "url"?: string;
    }
    interface IntrinsicElements {
        "ng-component": NgComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ng-component": LocalJSX.NgComponent & JSXBase.HTMLAttributes<HTMLNgComponentElement>;
        }
    }
}
